export { default as IconChat } from './chat.svg'
export { default as IconCrop } from './crop.svg'
export { default as IconMagic } from './magic.svg'
export { default as IconPhotos } from './photos.svg'

export { default as LogoYoutube } from './Youtube_Logo.svg'
export { default as LogoInstagram } from './Instagram_Logo.svg'
export { default as LogoLinkedIn } from './LinkedIn_Logo.svg'
export { default as LogoX } from './X_Logo.svg'

export { default as BackgroundNotfound } from './404background.svg'

// Chat
export { default as IconAI } from './ai.svg'
export { default as SendIcon } from './send.svg'
export { default as CopyIcon } from './copy.svg'
export { default as DislikeIcon } from './dislike.svg'
export { default as ExchangeIcon } from './exchange.svg'
export { default as SparklesIcon } from './sparkles.svg'
export { default as VolumeUpIcon } from './volume-up.svg'
export { default as DiagonalArrowIcon } from './diagonal-arrow.svg'

// Instruments page
export { default as RemoveBackgroundIcon } from './remove_background.svg'
export { default as InstantBackgroundsIcon } from './instant_backgrounds.svg'
export { default as RetouchIcon } from './retouch.svg'
export { default as ExpandIcon } from './expand.svg'
export { default as InstantShadowsIcon } from './instant_shadows.svg'
export { default as BlurBackgroundIcon } from './blur_background.svg'
export { default as ColorBackgroundIcon } from './color_background.svg'
export { default as ResizeIcon } from './resize.svg'
export { default as TextToPhotoIcon } from './text_to_photo.svg'
export { default as BatchIcon } from './batch.svg'
export { default as RoundProfileIcon } from './round_profile_picture.svg'
export { default as StickersToPhotoIcon } from './stickers_to_photo.svg'
export { default as TextIcon } from './text_7392456.svg'
export { default as ColorSplashIcon } from './lifebuoy.svg'
export { default as SwatchbookIcon } from './swatchbook.svg'
export { default as AdjustIcon } from './adjust.svg'
export { default as BobbleHeadIcon } from './bobble_head.svg'
export { default as RoundIcon } from './round_16179374.svg'
export { default as RgbIcon } from './rgb_7213068.svg'

export { default as GoogleLogo } from './google.svg'
export { default as FacebookLogo } from './facebook.svg'
export { default as AppleLogo } from './apple.svg'
export { default as LeftArrowIcon } from './LeftArrow.svg'

// Popover Header
export { default as DollarIcon } from './Dollar.svg'
export { default as DollarGreyIcon } from './DollarGrey.svg'
export { default as GroupIcon } from './Group.svg'
export { default as SettingIcon } from './Settings.svg'
export { default as DialogIcon } from './Dialog.svg'
export { default as ExitIcon } from './Exit.svg'

export { default as DiamondIcon } from './Diamond.svg'
export { default as DiamondGreyIcon } from './DiamondGrey.svg'
export { default as DiamondGoldIcon } from './DiamondGold.svg'
export { default as BigDiamondIcon } from './BigDiamond.svg'
export { default as StarIcon } from './Star5.svg'
export { default as PlusIcon } from './PlusIcon.svg'
export { default as MinusIcon } from './MinusIcon.svg'
export { default as Group2Icon } from './Group2.svg'
export { default as WalletMoneyIcon } from './WalletMoney.svg'

export { default as EmojiRocket } from './EmojiRocket.svg'
export { default as EmojiThumb } from './EmojiThumb.svg'
export { default as EmojiFire } from './EmojiFire.svg'
export { default as CheckSquareIcon } from './CheckSquare.svg'

export { default as ShieldStarIcon } from './ShieldStar.svg'
export { default as IncognitoIcon } from './Incognito.svg'
export { default as CloseSquareIcon } from './CloseSquare.svg'
export { default as SaleIcon } from './Sale.svg'
export { default as ClockCircleIcon } from './Clock Circle.svg'
export { default as PromoArrow } from './PromoArrow.svg'
