import type { Metadata } from "next";
import "../styles/sds/index.scss";
import { Inter } from "next/font/google";
import localFont from 'next/font/local'
import "../styles/index.scss";
import { Footer, Header } from "@/components/ui/compositions";
import { AntdRegistry } from "@ant-design/nextjs-registry";

const inter = Inter({ subsets: ["latin"], variable: '--font-inter' });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Muller = localFont({
  variable: '--font-muller',
  src: [
    {
      path: '../fonts/MullerBoldItalic.woff2',
      weight: '700',
      style: 'italic',
    }
  ],
})

const GothamPro = localFont({
  variable: '--font-gotham',
  src: [
    {
      path: '../fonts/GothamPro-BoldItalic.woff2',
      weight: '700',
      style: 'italic',
    }
  ],
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${GothamPro.variable} ${Muller.variable}`}>
      <body>
        <AntdRegistry>
          <Header />
          {children}
          <Footer />
        </AntdRegistry>
      </body>
    </html>
  );
}
